import esbuild from 'esbuild';
import { existsSync } from 'node:fs';
import { copyFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const production = process.argv[2] === 'production';
const outfile = 'main.js';
const manifest = 'manifest.json';

function resolveDevVaultPluginDir(): string | undefined {
	const vault = process.env.PAPERA_DEV_VAULT;

	if (!vault) {
		return undefined;
	}

	if (!existsSync(vault)) {
		throw new Error(`PAPERA_DEV_VAULT points at a folder that does not exist: ${vault}`);
	}

	return path.join(vault, '.obsidian', 'plugins', 'papera');
}

function copyToDevVault(pluginDir: string): esbuild.Plugin {
	return {
		name: 'copy-to-dev-vault',
		setup(build) {
			build.onEnd(async () => {
				await mkdir(pluginDir, { recursive: true });
				await copyFile(outfile, path.join(pluginDir, outfile));
				await copyFile(manifest, path.join(pluginDir, manifest));
			});
		},
	};
}

const devVaultPluginDir = resolveDevVaultPluginDir();

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
	],
	format: 'cjs',
	platform: 'browser',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: production ? false : 'inline',
	treeShaking: true,
	outfile,
	minify: production,
	plugins: devVaultPluginDir ? [copyToDevVault(devVaultPluginDir)] : [],
});

if (production) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
